### ISSUE TITLE
Template enhancements and improvements

### ISSUE THREAD

**Issue by harry-olabs** [harry-olabs/avi-hub#16]
### Description
Enhance the template codes with proper structuring for page/style assets.

### TODO

- [x] Update title for each page template
  - [x] Login title -> `Login`
  - [x] Registration -> `Registration`
  - [x] Dashboard -> `Dashboard`
  - [x] Manage Users -> `User Management`
  - [x] Employee profile -> `Employee Profile`
- [x] Start using CSS variables 
  - [x] Create a new css file called `variables.css`, and in the new file
  - [x] Create variables for:
    - [x] all colors used each template page
    - [x] `font-family` (the montserrat value)
    - [x] `font-size` (15px)
    - [x] `text-bold` (which is `500`)
  - [x] Replace the color values with their respective variable

### NOTE:

Use this convention when naming your variables:

If used for one purpose:

```css
--main-bg-color: #f1f1f1;
--avatar-border: 2px solid  #d15267;
```

If it is used in different element:

```css
--primary-gray: #dddddd;
--primary-gray-10: #cccccc;
--primary-gray-20: #eeeeee;
--primary-red: #d15267;
```
