### ISSUE TITLE
User Authentication | Implement signup functionality

### ISSUE THREAD

**Issue by harry-olabs** [harry-olabs/avi-hub#39]
As a new user, I should be able to register a new account profile.

### TODOs:

- [ ] Consume the API to signup a new user account
- [ ] Make use of Fetch API for HTTP request
- [ ] Store access token using cookies storage (**NOTE**: Not local storage)
- [ ] Upon successful signup, redirect them to the Dashbaord page
- [ ] Implement a guard to protect all the dashboard pages in such a way that it is only accessible by authenticated users (users with an `accessToken`)

### API Details

**API Domain:** https://afrihub-backend.onrender.com
**Signup API:** `POST` https://afrihub-backend.onrender.com/api/auth/signup

**Request Body:**
| Key  | Type |
| ---- | ----- |
| firstName  | string  |
| lastName | string  |
| email  | string  |
| password | string  |

**Response Payload**
```
{ accessToken: '__ACCESS_TOKEN__' }
```
