### ISSUE TITLE
User Authentication | Implement login functionality

### ISSUE THREAD

**Issue by harry-olabs** [harry-olabs/avi-hub#40]
As a registered user, I should be able to login with my email and password.

### TODOs:

- [ ] Consume the API to login a registered user account
- [ ] Make use of Fetch API for HTTP request
- [ ] Persist access token in using cookies storage (**NOTE**: Not localStorage)
- [ ] Upon successful login, redirect user to the Dashbaord page
- [ ] Dashboard pages should only be accessible by authenticated users (users with an `accessToken`)

### API Details

**API Domain:** https://afrihub-backend.onrender.com
**Signup API:** `POST` https://afrihub-backend.onrender.com/api/auth/login

**Request Body:**
| Key  | Type |
| ---- | ----- |
| email  | string  |
| password | string  |

**Response Payload**
```
{ accessToken: '__ACCESS_TOKEN__' }
```
