### ISSUE TITLE
Dashboard | Implement logic to display logged-in user profile

### ISSUE THREAD

**Issue by harry-olabs** [harry-olabs/avi-hub#41]
As a new user, I should be able to see my name on the dashboard when I login with my account.

### TODOs:

- [ ] Consume the API to fetch auth user details
- [ ] Send `accessToken` as Bearer Token in the request header
  - [ ] Authorization: Bearer `ACCESS_TOKEN`
- [ ] Update static content on the dashboard to the user firstName and lastName.

### API Details

**API Domain:** https://afrihub-backend.onrender.com
**Signup API:** `GET` https://afrihub-backend.onrender.com/api/auth/me

**Request Header**
| Key  | Value |
| ---- | ----- |
| Authorization  | Bearer `ACCESS_TOKEN`  |

**Response Payload**
```json
{
    "id": 11,
    "firstName": "John",
    "lastName": "Doe",
    "email": "test@example.com",
    "createdAt": "2023-08-28T21:58:35.255Z",
    "updatedAt": "2023-08-28T21:58:35.255Z"
}
```
